# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ed1edfa155dd2cd362612c391115f0a49eab32b31b4542a37a109664b965ce9a105b1ea5eb039b5f30447533ccfc14eb114219ea4eef70799950b665bf9e3921

test:
  secret_key_base: 5ed71e5a8706140ddffda5f5bfca6c10dec1bf31c02b38d8465ec233c01bae4ba897b6c456a2dee63614b7e57a89ed37057d44be067eff0bb6050d6211f16356

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
